# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d7de7a2711efa90d3fc5af62186389dd5859f25b5f99a3bd2209a3fe73a2d5b2f5a0642966a81c381089f4a7cabd3f8cdbf6cd0f966402a9d5e28bb674b6e0e

test:
  secret_key_base: 706001a7169899a2403e4ab9a3d5ca8185b96c548d6f76f9db29ca2eb8b4e4749a8dd9b5a35e8350a287a25154ae9588b93c049749544d47407e856937ce3b5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
